name: Deploy to Hugging Face Space

on:
  push:
    branches:
      - main # Or your desired branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Push to Hugging Face Space
        uses: huggingface/actions/space-push@v2
        with:
          hf_token: ${{ secrets.HF_TOKEN }}
          space_id: alistermarc/resume-chatbot